//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPSParks.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking
    {
        public int sensorID { get; set; }
        public int floorID { get; set; }
        public string regionID { get; set; }
        public bool isTaken { get; set; }
    }
}
